### ISSUE TITLE
Error with v2.1.0

### ISSUE THREAD

**Issue by JamesChevalier** [kt3k/update-pr-description#14]
```
Looking up a pull request #undefined
Error: Cannot update the pull request.
Error: HttpError: Not Found
    at /home/runner/work/_actions/kt3k/update-pr-description/v2/node_modules/@octokit/request/dist-node/index.js:86:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (/home/runner/work/_actions/kt3k/update-pr-description/v2/index.js:44:30)
```

Specifying `uses: kt3k/update-pr-description@v2.0.0` in my workflow file resolves the issue.

I'm in the middle of working on some other stuff, so I can't work on debugging this right now. I wanted to at least get the issue reported.

**Comment by kt3k** [comment]
Thanks for reporting.

I'll revert #13 for now.

**Comment by kt3k** [comment]
release v2.1.1
